# Generated by Django 3.2 on 2022-01-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
    ]
